name: tic_tac_toe_console
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  equatable: ^2.0.5
  tic_tac_toe_lib:
    path: '../tic_tac_toe_lib'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
